### ISSUE TITLE
[model] Validation messages returned from api/schemas

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2#11]
The valdidation messages returned by the schemas api are not very enduser friendly and are not identifiable by some sort of type. (Required, length)

Either translate the messages returned by the schema validator to something more user friendly or perhaps we can add a type to these messages `"type": "required"` so we can generate our own type messages.

``` json
[
    {
        "message": "Allowed range for length [8, 8], length is 6",
        "property": "publicAccess",
        "value": "rw----"
    },
    {
        "message": "Required property missing.",
        "property": "shortName"
    }
]
```

**Comment by mortenoh** [comment]
I'm planing to expand this in 2.20. Feel free to suggest formats, it will also be wrapped in a WebMessage (we have a blueprint for wrapping all messages from the web-api in webMessage in 2.20)

We should probably introduce coded validation messages also, make it a lot easier.
