### ISSUE TITLE
Problem with field userRole.authorities 

### ISSUE THREAD

**Issue by tokland** [dhis2/d2#130]
Whether I create or update a user role, the _authorities_ field is not set. An example:

```
userRose = d2.models.userRoles.create({name: "Name", authorities: ["ALL"]})
userRole.create();
```

Looking at the request, I can see that the field _authorities_ is sent as an empty array. I think the problem's here:

https://github.com/dhis2/d2/blob/v26/src/model/helpers/json.js#L53

It's my understanding that `authorities` is a non-model-collection (since it's a plain array of strings), so it should be added to `NON_MODEL_COLLECTIONS`.

**Comment by Markionium** [comment]
That is a correct indeed! :)

If you're working with the user models you might find some other quirks that don't won't really work. We have not used it a lot with `roles` `groups` and `users` yet. So if you do find other things, let us know!

**Comment by Markionium** [comment]
@tokland you should be able to use https://github.com/dhis2/d2/releases/tag/v26.2.2

**Comment by tokland** [comment]
That was fast, @Markionium, thx!
