### ISSUE TITLE
Collection element deletion does not set parent 'dirty'

### ISSUE THREAD

**Issue by Awnage** [dhis2/d2#132]
Assumption: OU Group (pVQY1GElA6k) exists with member OU (Y5t61UqAC3x)
```
let ougUID = 'pVQY1GElA6k';
let ouUID = 'Y5t61UqAC3x';
d2.models.organisationUnitGroup.get(ougUID)
  .then(oug=>{ 
        d2.models.organisationUnit.get(ouUID)
            .then(ou=>{
                 oug.organisationUnits.delete(ou.id);
                 oug.save().then(res=>{
                     console.log('res',res);  
                    // res is {}, network monitor shows no data transfer
                    // refreshing the maintenance the member still exists.
                 });
             });
});
```
Adding in a `oug.dirty=true;` gets it to save, but that seems to be unexpected behavior. I assume this is the case with other object types as well.

**Comment by nicolayr** [comment]
Does it work correctly with `.remove(ou.id);` instead of `.delete` ?

**Comment by Awnage** [comment]
Close. `.remove(Model)` is in `ModelCollectionProperty.js`. Thank you.

**Comment by nicolayr** [comment]
It's not ideal that `.delete` is inherited from `ModelCollection` but doesn't actually work correctly for `ModelCollectionProperty` though. It should probably be overridden.
