### ISSUE TITLE
Replace jQuery dependency

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2#35]
Since we only use the ajax part, it would be nice to replace with something else.

**Comment by mortenoh** [comment]
Can I suggest w3c fetch? I use it all the time in my apps, and there is
both native support (in chrome) and polyfills available

--
Morten

**Comment by nicolayr** [comment]
@mortenoh that does seems like the way to go :+1:

**Comment by Markionium** [comment]
Yes that was originally my idea as well.

The syntax is also quite similar so we should be able to do that fairly easy.

**Comment by Markionium** [comment]
Make sure to refactor stuff that goes around the `Api` object to jQuery directly.

https://github.com/dhis2/d2/blob/7f71b3c6fa89d5bb790720231149924b76778043/src/d2.js#L9
https://github.com/dhis2/d2/commit/ebf0c5f71318a61eb78426776a43d20868d588fb#diff-ce297cf7af0758030cb8e402653c494eR103

**Comment by nicolayr** [comment]
An alternative to fetch, with support for progress events: [axios](https://github.com/mzabriskie/axios)
The API is very similar to jQuery, but it's a minimal XMLHttpRequest wrapper.
