### ISSUE TITLE
Add proper userSettings object

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2#44]
Currently the only userSetting that is loaded is the `keyUiLocale`

We should probably have a proper UserSettings object where settings can be queried.

One additional one that should be loaded up front is the userStyle as that is required for the headerbar/ui styling

**Comment by adhbh** [comment]
@Markionium @nicolayr 
Possible duplicate issues?  https://github.com/dhis2/d2/issues/72 . Do we still need userStyle to be uploaded upfront?

**Comment by nicolayr** [comment]
Since all user settings can be fetched from the API with one query now (it wasn't before), it's no longer necessary to treat `userStyle` (which has been renamed to `keyStyle`) in a special way.

And yes, this is definitely a duplicate of #72 - so I'm closing this one :)
