### ISSUE TITLE
Remove quasi-settings from settingsKeyMapping.js

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2#51]
See https://github.com/dhis2/d2/commit/3422b284e62a99ca62f2db2492635f4320f86115

**Comment by Markionium** [comment]
Perhaps this could be integrated into a component that groups the email-settings?

**Comment by nicolayr** [comment]
The settings key mapping has been moved to the settings app (e1c6a79af9e96bcfc9ed43caf4739b7b48be6224).
