### ISSUE TITLE
Getting sharing information

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2#52]
Support getting the proper sharing information for an object.

To currently get the sharing information for an object one needs to call the `/api/sharing` endpoint. The actual sharing information is also available on the object itself, but there the userGroup names are not included, so those would have to be retrieved separately. Therefore using the `api/sharing` endpoint is currently more convenient.

**Comment by mortenoh** [comment]
Hi

If you all you need is the user group name, I'm sure we can expose that. We
can't expose the user group object directly because of circular references
(it could possibly be fixed, but easier to just expose user group name if
that helps you). One less request is always good..

--
Morten

**Comment by Markionium** [comment]
That would help i presume. Currently it returns the `name` property on the `/api/sharing` endpoint. Ideally this should probably be the `displayName`. But because groups can not be translated i guess they are always the same?

**Comment by mortenoh** [comment]
I added a few changes now, please try with latest version. I'm exporting
displayName as both name (as before) and displayName, I don't want to break
anything just before release.. but feel free to use displayName instead..
both at the sharing endpoint, and also user group accesses directly on the
objects..

I made a few other changes, please have a look..

--
Morten
