### ISSUE TITLE
Bulk Creation of objects

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2#56]
RBF Guys might want to use D2 for their new app but will need to do some bulk creation/updates of objects.

One idea might be to create a `ModelCollection` and add `Model` instances to it, while then calling `save()` on the collection. This should do a `POST` to the relevant endpoint and create multiple metadata objects.

An alternative could be to just use an array and have static save method to which the collection gets passed.

**Comment by Awnage** [comment]
I would certainly like to see this as well. Currently it is not possible with d2 to create models with a specified ID, which a lot of bulk creation would need.

**Comment by Markionium** [comment]
It's on the list for v25. 

We'll likely implement something like the following

```js
// Saving models of one type
d2.models.dataElements.save([ Model, Model ]);
// Potentially allow mix and match models of different types using the /api/metadata import endpoint
d2.models.save([ Model, Model, Model ]);
```
