### ISSUE TITLE
Use consistent error format and logging behaviour

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2#59]
At the moment logging and error reporting behaviour in D2 is erratic.

We should define a consistent behaviour for what logging is done by D2 itself, as well as a consistent error reporting format.

It's probably a good idea to introduce differentiated behaviour between production and development build as well, along the lines of what React does.

For example if D2 fails to initialise, it currently logs an error to the console and then rejects the promise with the jqXHR object from jQuery. This has several problems: It leaks the dependency on jQuery to the client app, it doesn't provide the client app with any useful information about why the initialisation failed, and it prevents the client app from controlling what's logged to the console.

In stead, any jQuery errors should be handled by D2 itself, and the promise should be rejected with a predictable error format that can be parsed by the client application. D2 probably shouldn't do any logging itself, unless it's a development build.

For example, the settings app would work like this (roughly):

```js
getManifest("my_manifest.json")
  .then(manifest => { config.baseUrl = manifest.getBaseUrl() + '/api'; })
  .then(getUserSettings)
  .then(configI18n)
  .then(init)
  .then(d2 => { console.log("D2 initialised successfully!"); })
  .catch(error => { console.error("D2 failed to initialise: " + error.message); })
```

**Comment by Markionium** [comment]
This sounds good. Lets do this at the same time when we take care of https://github.com/dhis2/d2/issues/35
