### ISSUE TITLE
Model.dirty is false even though the Model has a dirty ModelPropertyCollection

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2#66]
At the moment Model.dirty is a simple boolean property on the Model object.

I can see two natural ways of addressing this issue: Either we can treat `Model.dirty` as private and add a method such as `Model.isDirty()` which checks both `this.dirty` and any ModelPropertyCollections on the object, or change `Model.dirty` into a dynamic getter.

I'm not sure what the best solution is. Making `Model.dirty` a dynamic getter is in line with how we do other getters on models at the moment. However, having an explicit method like `Model.isDirty()` is probably easier to reason about for new developers than a magic property.

**Comment by Markionium** [comment]
This is currently resolved by checking the model itself plus the children individually. Which is not really the cleanest way of doing things.

https://github.com/dhis2/d2/blob/feature-collection-props/src/model/ModelBase.js#L28

I think if we go for the `Model.isDirty()` solution that check could be in there. However there still should be a way to set the dirty state. I'm not sure if we should hide that property totally or allow it to be set directly (also externally)
