### ISSUE TITLE
Inactivity in apps causes the requests to "fail"

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2#68]
The new apps build on top of `d2` stop working when the session is expired.

Because these apps are not served though the api. The app keeps working due to its SPA nature, but the requests to the api return the _html_ login page.

We might have to check the responses of the ajax requests for the login page and somehow reject the promise with the correct message.

**Comment by nicolayr** [comment]
Perhaps this is one of those things that it would be better to fix in the API?

**Comment by Markionium** [comment]
Agreed, but it has been like this for more than 2 years. So a solution will probably take time :P

The solution to this from our side will be quite hacky. But since it is only in the `Api` class it might be a decent temporary solution.

**Comment by mortenoh** [comment]
What we did in data entry (not really saying this is ideal), was to ping
the server at a given interval. Something like "GET /api/system/ping",
which would return "pong" if all is OK.

I think doing this every 15 min or so would be enough, the session times
out after.. 1 hour I think now?

Its not really a nice solution, but it gets the job done. Of course, you
-should- handle expired sessions also.

On Wed, Feb 10, 2016 at 7:22 PM, Mark Polak <notifications@github.com>
wrote:

> Agreed, but it has been like this for more than 2 years. So a solution
> will probably take time :P
>
> The solution to this from our side will be quite hacky. But since it is
> only in the Api class it might be a decent temporary solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhis2/d2/issues/68#issuecomment-182344873>.
>



-- 
Morten
