### ISSUE TITLE
Api Collections can be ordered or unordered

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2#70]
The `COLLECTION` propertyType in schemas endpoint can refer to an ordered list (`java.util.List`) or a unordered list (`java.util.set`).

This might be important when rendering a ui widget for a collection. In case of the d2-ui `<GroupEditor />` whether to show ordering buttons or not. The `ModelCollection`/`ModelCollectionProperty` should be enhanced with an `isOrdered()` function and perhaps the ability to re-order (either based on a given list of uids or a new order of the `Model` objects).

Determining whether a list is an ordered list or an unordered list seems currently only possible by checking the `klass` property which refers to the Java class.

A temporary solution could be to work off that `klass` property while perhaps an  `isOrdered` or `ordered` property could be added to the schema properties.

**Comment by mortenoh** [comment]
A property called ordered can now be found in latest 2.22 and trunk.

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org
