### ISSUE TITLE
Get complete userSettings

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2#72]
`d2.currentUser.userSettings` should be populated with the complete user settings (from `/api/userSettings`) rather than just the `keyUiLocale` setting

**Comment by adhbh** [comment]
starting to work on this :+1:

**Comment by Markionium** [comment]
Something to note:

There seems to be some trouble here on the latest dev version..
https://play.dhis2.org/demo/api/userSettings.json (Seems to return a correct payload) 

The dev version however gives a shiny stack trace.
https://play.dhis2.org/dev/api/userSettings.json

I'll submit a bug report for this on launchpad.

**Comment by mortenoh** [comment]
Please try again in 30 min

-- 
Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org

**Comment by Markionium** [comment]
Ah just submitted a bug. Will mark that invalid when it works ;)

**Comment by nicolayr** [comment]
Fixed by pull request #73 from @adhbh - thanks! 👍
