### ISSUE TITLE
OU bad creation responds 200 and leads to additional invalid network calls

### ISSUE THREAD

**Issue by Awnage** [dhis2/d2#76]
I do realize that specifying the myModel.id is causing this, but there my be other ways of generating this error.

**How to replicate:**

```
let myModel = Model.create(d2.models.organisationUnit);
myModel.id='A0000000001';
myModel.name="My OU";
myModel.shortName="mou";
myModel.openingDate="2015-01-01";
myCollection.add(myModel);
```

The 200 response contains:

```
{
  "httpStatus":"OK",
  "httpStatusCode":200,
  "status":"OK",
  "response":{"responseType":"ErrorReports"}
}
```

As there is no id returned, the library continues on its way, calling
`https://MYSERVER/api/undefined?mergeMode=REPLACE`
which generates a 404.

**Expected behavior:**
d2 should detect the lack of an UID int he response and prevent any following "undefined" calls.

**Comment by Markionium** [comment]
Thanks for reporting! :) That does not look like a correct server response, there have been some recent changes where this was adjusted on the server side.

I agree that we should not allow the library to continue. Will fix and throw a proper error.
